version: 2
config_android: &config_android
  docker:
    - image: circleci/android:api-28-alpha
  working_directory: ~/project
  environment:
    JAVA_TOOL_OPTIONS: -Xmx1024m
    GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Dkotlin.incremental=false
    TERM: dumb

jobs:
  build_and_setup:
    <<: *config_android
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: echo $FABRIC_API_SECRET >> "MyAppFolder/app/fabric.properties"
      - restore_cache:
          key: jars-{{ checksum "MyAppFolder/build.gradle" }}-{{ checksum  "MyAppFolder/app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          working_directory: MyAppFolder
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "MyAppFolder/build.gradle" }}-{{ checksum  "MyAppFolder/app/build.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew lint
          working_directory: MyAppFolder
      - run:
          name: Run Tests
          command: ./gradlew test
          working_directory: MyAppFolder
      - run:
          name: build dev app
          command: ./gradlew assembleDebug crashlyticsUploadDistributionDebug
          working_directory: MyAppFolder
      - run:
          name: build prod app
          command: ./gradlew assembleRelease crashlyticsUploadDistributionRelease
          working_directory: MyAppFolder
      - store_artifacts:
          path: MyAppFolder/app/build/outputs
          destination: outputs
      - store_artifacts:
          path: MyAppFolder/app/build/reports
          destination: reports
      - store_test_results:
          path: MyAppFolder/app/build/test-results
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_setup


